[package]
name = "ash-raytracing-example"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.33.0"
png = "0.16.8"

[build-dependencies]
spirv-builder = "0.9"
